/** Autogenerated Main.cpp. */

// =================================| Include only the DSP files  |=================================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ===========================| Now we can add the rest of the codebase |===========================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// =======================================| Project Factory |=======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ----------------------------------------------------------------------
		
		registerPolyNode<project::svf_peak<1>, scriptnode::wrap::illegal_poly<project::svf_peak<1>>>();
		registerPolyNode<project::svf_hp<1>, scriptnode::wrap::illegal_poly<project::svf_hp<1>>>();
		registerPolyNode<project::noise<1>, scriptnode::wrap::illegal_poly<project::noise<1>>>();
		registerPolyNode<project::svf_ls<1>, scriptnode::wrap::illegal_poly<project::svf_ls<1>>>();
		registerPolyNode<project::svf_hs<1>, scriptnode::wrap::illegal_poly<project::svf_hs<1>>>();
		registerPolyNode<project::svf_lp<1>, scriptnode::wrap::illegal_poly<project::svf_lp<1>>>();
		registerPolyNode<project::loopfadeplayer<1>, project::loopfadeplayer<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::hardsoftclipper<1>, wrap::illegal_poly<project::hardsoftclipper<1>>>();
		registerDataNode<project::sntumult_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


