/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "loopfadeplayer.h"
#include "svf_lp.h"
#include "svf_hs.h"
#include "svf_ls.h"
#include "noise.h"
#include "svf_hp.h"
#include "svf_peak.h"

// Include compiled network files ------------------

#include "hardsoftclipper.h"
#include "sntumult_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

